/**
 * Curated Hán-Việt readings used by lessons 1–50.
 * Base data: ph0ngp/hanviet-pinyin-wordlist (MIT); Japanese variants
 * are normalized with Unicode Unihan 17.0 and reviewed for lesson context.
 */
import { additionalHanViet } from './han-viet-n4.ts';
const hanVietReadings: Record<string, string[]> = {
  ...additionalHanViet,
  一: ['nhất'],
  七: ['thất'],
  万: ['vạn'],
  丈: ['trượng'],
  三: ['tam'],
  上: ['thượng'],
  下: ['hạ'],
  不: ['bất'],
  世: ['thế'],
  両: ['lưỡng'],
  中: ['trung'],
  丸: ['hoàn'],
  丼: ['tỉnh', 'đảm'],
  乗: ['thừa'],
  九: ['cửu'],
  久: ['cửu'],
  低: ['đê'],
  口: ['khẩu'],
  妻: ['thê'],
  百: ['bách'],
  穴: ['huyệt'],
  貼: ['thiếp'],
  寮: ['liêu'],
  渇: ['khát'],
  確: ['xác'],
  認: ['nhận'],
  夢: ['mộng'],
  湯: ['thang'],
  乳: ['nhũ'],
  乾: ['càn', 'kiền', 'can'],
  予: ['dư', 'dữ'],
  事: ['sự'],
  二: ['nhị'],
  五: ['ngũ'],
  交: ['giao'],
  京: ['kinh'],
  人: ['nhân'],
  今: ['kim'],
  介: ['giới'],
  仕: ['sĩ'],
  付: ['phó'],
  伎: ['kỹ'],
  休: ['hưu'],
  会: ['hội'],
  伝: ['truyền'],
  住: ['trú', 'trụ'],
  体: ['thể'],
  何: ['hà'],
  作: ['tác'],
  使: ['sử', 'sứ'],
  価: ['giá'],
  便: ['tiện'],
  保: ['bảo'],
  信: ['tín'],
  修: ['tu'],
  借: ['tá', 'tịch'],
  値: ['trị'],
  健: ['kiện'],
  傘: ['tản'],
  備: ['bị'],
  働: ['động'],
  僕: ['bộc'],
  億: ['ức'],
  元: ['nguyên'],
  兄: ['huynh'],
  先: ['tiên'],
  入: ['nhập'],
  全: ['toàn'],
  八: ['bát'],
  公: ['công'],
  六: ['lục'],
  内: ['nội'],
  円: ['viên'],
  写: ['tả'],
  冬: ['đông'],
  冷: ['lãnh'],
  出: ['xuất'],
  分: ['phân', 'phận', 'phần'],
  切: ['tiếp', 'thiết'],
  初: ['sơ'],
  別: ['biệt'],
  利: ['lợi'],
  刺: ['thích', 'thứ'],
  刻: ['khắc'],
  前: ['tiền'],
  加: ['gia'],
  勉: ['miễn', 'mẫn'],
  動: ['động'],
  務: ['vụ'],
  勝: ['thắng'],
  勤: ['cần'],
  北: ['bắc'],
  医: ['y'],
  十: ['thập'],
  千: ['thiên'],
  午: ['ngọ'],
  半: ['bán'],
  単: ['đơn'],
  危: ['nguy'],
  卵: ['noãn'],
  去: ['khứ', 'khử'],
  参: ['tam', 'tham', 'sâm'],
  友: ['hữu'],
  取: ['thủ'],
  受: ['thụ'],
  古: ['cổ'],
  台: ['đài'],
  右: ['hữu'],
  号: ['gào', 'hào', 'hiệu'],
  合: ['hợp'],
  同: ['đồng'],
  名: ['danh'],
  君: ['quân'],
  吸: ['hấp'],
  呂: ['lữ', 'lã'],
  味: ['vị'],
  呼: ['hô'],
  和: ['hoà', 'hoạ', 'ù', 'hồ'],
  品: ['phẩm'],
  員: ['viên'],
  問: ['vấn'],
  喫: ['khiết'],
  四: ['tứ'],
  回: ['hồi'],
  団: ['đoàn'],
  困: ['khốn'],
  図: ['đồ'],
  国: ['quốc'],
  園: ['viên'],
  土: ['thổ'],
  地: ['địa'],
  城: ['thành'],
  堂: ['đường'],
  場: ['tràng', 'trường'],
  塩: ['diêm'],
  士: ['sĩ'],
  売: ['mại'],
  変: ['biến'],
  夏: ['hạ'],
  夕: ['tịch'],
  外: ['ngoại'],
  多: ['đa'],
  夜: ['dạ'],
  大: ['đại'],
  天: ['thiên'],
  太: ['thái'],
  夫: ['phu', 'phù'],
  失: ['thất'],
  奈: ['nại'],
  奥: ['ảo', 'áo'],
  女: ['nữ'],
  好: ['hảo', 'hiếu'],
  妹: ['muội'],
  姉: ['tỷ'],
  始: ['thủy'],
  婚: ['hôn'],
  嫌: ['hiềm'],
  子: ['tử', 'tý'],
  字: ['tự'],
  季: ['quý'],
  学: ['học'],
  安: ['an'],
  定: ['định'],
  実: ['thực'],
  客: ['khách'],
  室: ['thất'],
  家: ['gia'],
  宿: ['túc', 'tú'],
  寂: ['tịch'],
  富: ['phú'],
  寒: ['hàn'],
  寝: ['tẩm'],
  察: ['sát'],
  寺: ['tự'],
  封: ['phong'],
  専: ['chuyên'],
  小: ['tiểu'],
  少: ['thiểu', 'thiếu'],
  局: ['cục'],
  屋: ['ốc'],
  山: ['sơn'],
  島: ['đảo'],
  川: ['xuyên'],
  工: ['công'],
  左: ['tả'],
  差: ['sai'],
  市: ['thị'],
  布: ['bố'],
  師: ['sư'],
  帰: ['quy'],
  帳: ['trướng'],
  帽: ['mạo'],
  年: ['niên'],
  幹: ['cán'],
  広: ['quảng'],
  床: ['sàng'],
  店: ['điếm'],
  度: ['độ', 'đạc'],
  座: ['toạ', 'toà'],
  庫: ['khố'],
  庭: ['đình'],
  康: ['khang'],
  廊: ['lang'],
  建: ['kiến'],
  引: ['dẫn'],
  弟: ['đệ'],
  弱: ['nhược'],
  張: ['trương'],
  強: ['cường', 'cưỡng'],
  弾: ['đạn'],
  当: ['đương', 'đáng'],
  役: ['dịch'],
  彼: ['bỉ'],
  待: ['đãi'],
  後: ['hậu'],
  心: ['tâm'],
  必: ['tất'],
  忘: ['vong'],
  忙: ['mang'],
  念: ['niệm'],
  思: ['tư', 'tứ'],
  急: ['cấp'],
  悪: ['ác'],
  意: ['ý'],
  所: ['sở'],
  手: ['thủ'],
  払: ['phất'],
  押: ['áp'],
  持: ['trì'],
  捨: ['xả'],
  掃: ['tảo'],
  探: ['thám'],
  換: ['hoán'],
  撮: ['toát'],
  撲: ['phác'],
  政: ['chính'],
  故: ['cố'],
  教: ['giáo', 'giao'],
  散: ['tản', 'tán'],
  数: ['số'],
  文: ['văn'],
  料: ['liệu'],
  新: ['tân'],
  方: ['phương'],
  旅: ['lữ'],
  族: ['tộc'],
  日: ['nhật'],
  早: ['tảo'],
  明: ['minh'],
  易: ['dịch', 'dị'],
  昔: ['tích'],
  映: ['ánh'],
  春: ['xuân'],
  昨: ['tạc'],
  昼: ['trú'],
  時: ['thời'],
  晩: ['vãn'],
  暇: ['hạ'],
  暑: ['thử'],
  暖: ['noãn'],
  暗: ['ám'],
  暮: ['mộ'],
  曇: ['đàm'],
  曜: ['diệu'],
  曲: ['khúc'],
  書: ['thư'],
  最: ['tối'],
  月: ['nguyệt'],
  有: ['hữu'],
  服: ['phục'],
  朝: ['triều'],
  木: ['mộc'],
  末: ['mạt'],
  本: ['bản'],
  机: ['cơ'],
  束: ['thúc'],
  来: ['lai'],
  杯: ['bôi'],
  東: ['đông'],
  枚: ['mai'],
  果: ['quả'],
  校: ['hiệu'],
  案: ['án'],
  桜: ['anh'],
  梅: ['mai'],
  械: ['giới'],
  棚: ['bằng'],
  業: ['nghiệp'],
  楽: ['lạc'],
  橋: ['kiều'],
  機: ['cơ'],
  次: ['thứ'],
  欲: ['dục'],
  歌: ['ca'],
  止: ['chỉ'],
  正: ['chính'],
  歩: ['bộ'],
  歯: ['xỉ'],
  歳: ['tuế'],
  残: ['tàn'],
  段: ['đoạn'],
  母: ['mẫu'],
  毎: ['mỗi'],
  気: ['khí'],
  水: ['thuỷ'],
  池: ['trì'],
  治: ['trị'],
  泊: ['bạc'],
  注: ['chú'],
  泳: ['vịnh'],
  洗: ['tẩy'],
  活: ['hoạt'],
  浴: ['dục'],
  海: ['hải'],
  消: ['tiêu'],
  涼: ['lương', 'lượng'],
  済: ['tế'],
  渡: ['độ'],
  温: ['ôn'],
  港: ['cảng'],
  準: ['chuẩn'],
  漢: ['hán'],
  濯: ['trạo', 'trạc'],
  点: ['điểm'],
  無: ['vô', 'mô'],
  然: ['nhiên'],
  焼: ['thiêu'],
  煙: ['yên'],
  熱: ['nhiệt'],
  父: ['phụ'],
  牛: ['ngưu'],
  牧: ['mục'],
  物: ['vật'],
  特: ['đặc'],
  犬: ['khuyển'],
  独: ['độc'],
  狭: ['hiệp'],
  猫: ['miêu'],
  玄: ['huyền'],
  現: ['hiện'],
  球: ['cầu'],
  理: ['lý'],
  甘: ['cam'],
  生: ['sinh'],
  産: ['sản'],
  用: ['dụng'],
  田: ['điền'],
  男: ['nam'],
  町: ['đinh'],
  画: ['họa'],
  界: ['giới'],
  留: ['lưu'],
  番: ['phan', 'phiên'],
  疲: ['bì'],
  病: ['bệnh'],
  痛: ['thống'],
  登: ['đăng'],
  白: ['bạch'],
  皆: ['giai'],
  目: ['mục'],
  直: ['trực'],
  相: ['tương', 'tướng'],
  県: ['huyện'],
  真: ['chân'],
  眠: ['miên'],
  眼: ['nhãn'],
  着: ['trước', 'trứ'],
  知: ['tri'],
  短: ['đoản'],
  砂: ['sa'],
  研: ['nghiên'],
  磨: ['ma', 'mài', 'má'],
  礼: ['lễ'],
  社: ['xã'],
  祈: ['kỳ'],
  祖: ['tổ'],
  神: ['thần'],
  祭: ['sái', 'tế'],
  禁: ['cầm', 'câm', 'cấm'],
  私: ['tư'],
  秋: ['thu'],
  究: ['cứu'],
  空: ['không', 'khống'],
  窓: ['song'],
  立: ['lập'],
  符: ['phù'],
  筆: ['bút'],
  筒: ['đồng'],
  答: ['đáp'],
  箱: ['tương', 'sương'],
  箸: ['trợ'],
  節: ['tiết'],
  簡: ['giản'],
  糖: ['đường'],
  約: ['yêu', 'ước'],
  紅: ['hồng', 'công'],
  納: ['nạp'],
  紙: ['chỉ'],
  細: ['tế'],
  紹: ['thiệu'],
  終: ['chung'],
  経: ['kinh'],
  結: ['kết'],
  絡: ['lạc'],
  統: ['thống'],
  絵: ['hội'],
  緑: ['lục'],
  線: ['tuyến'],
  練: ['luyện'],
  置: ['trí'],
  美: ['mỹ'],
  習: ['tập'],
  考: ['khảo'],
  者: ['giả'],
  耳: ['nhĩ'],
  聞: ['văn'],
  肉: ['nhục'],
  育: ['dục'],
  背: ['bối', 'bội'],
  脱: ['thoát'],
  自: ['tự'],
  舎: ['xá'],
  舞: ['vũ'],
  航: ['hàng'],
  船: ['thuyền'],
  良: ['lương'],
  色: ['sắc'],
  花: ['hoa'],
  若: ['nhược', 'nhã'],
  英: ['anh'],
  茶: ['trà'],
  荷: ['hà', 'hạ'],
  菓: ['quả'],
  菜: ['thái'],
  葉: ['diệp'],
  蔵: ['tàng'],
  薬: ['dược'],
  行: ['hàng', 'hạng', 'hành', 'hạnh'],
  術: ['thuật'],
  表: ['biểu'],
  袋: ['đại'],
  製: ['chế'],
  要: ['yêu', 'yếu'],
  見: ['kiến', 'hiện'],
  覚: ['giác'],
  親: ['thân', 'thấn'],
  角: ['giác', 'giốc', 'góc'],
  触: ['xúc'],
  言: ['ngôn'],
  計: ['kế'],
  記: ['ký'],
  証: ['chứng'],
  試: ['thí'],
  話: ['thoại'],
  誌: ['chí'],
  誕: ['đản'],
  語: ['ngữ', 'ngứ'],
  説: ['thuyết'],
  読: ['độc'],
  誰: ['thuỳ'],
  課: ['khoá'],
  調: ['điệu', 'điều'],
  談: ['đàm'],
  警: ['cảnh'],
  議: ['nghị'],
  豆: ['đậu'],
  豚: ['đồn'],
  象: ['tượng'],
  負: ['phụ'],
  買: ['mãi'],
  貸: ['thải'],
  賃: ['lẫm', 'nhẫm'],
  資: ['tư'],
  赤: ['xích'],
  起: ['khởi'],
  越: ['việt'],
  趣: ['thú'],
  足: ['tú', 'túc'],
  身: ['thân'],
  車: ['xa'],
  転: ['chuyển'],
  軽: ['khinh'],
  辛: ['tân'],
  辞: ['từ'],
  迎: ['nghênh'],
  近: ['cận'],
  返: ['phản'],
  送: ['tống'],
  通: ['thông'],
  速: ['tốc'],
  造: ['tạo'],
  連: ['liên'],
  週: ['chu'],
  遅: ['trì'],
  遊: ['du'],
  運: ['vận'],
  道: ['đạo'],
  達: ['đạt'],
  違: ['vi'],
  遠: ['viễn'],
  選: ['tuyển'],
  邪: ['tà'],
  部: ['bộ'],
  郵: ['bưu'],
  都: ['đô'],
  配: ['phối'],
  酒: ['tửu'],
  里: ['lý'],
  重: ['trùng', 'trọng'],
  野: ['dã'],
  金: ['kim'],
  釣: ['điếu'],
  鉄: ['thiết'],
  鉛: ['duyên'],
  銀: ['ngân'],
  録: ['lục'],
  鍵: ['kiện'],
  鏡: ['kính'],
  長: ['trường', 'trưởng'],
  門: ['môn'],
  閉: ['bế'],
  開: ['khai'],
  間: ['gian', 'gián'],
  関: ['quan'],
  阪: ['phản'],
  降: ['giáng', 'hàng'],
  院: ['viện'],
  除: ['trừ'],
  険: ['hiểm'],
  階: ['giai'],
  際: ['tế'],
  障: ['chướng'],
  隣: ['lân'],
  集: ['tập'],
  雑: ['tạp'],
  難: ['nan', 'nạn'],
  雨: ['vũ'],
  雪: ['tuyết'],
  電: ['điện'],
  青: ['thanh'],
  静: ['tĩnh'],
  靴: ['ngoa'],
  音: ['âm'],
  頑: ['ngoan'],
  領: ['lãnh'],
  頭: ['đầu'],
  題: ['đề'],
  顔: ['nhan'],
  願: ['nguyện'],
  風: ['phong'],
  飛: ['phi'],
  食: ['thực', 'tự'],
  飲: ['ẩm', 'ấm'],
  館: ['quán'],
  首: ['thủ', 'thú'],
  馬: ['mã'],
  駄: ['đà'],
  駅: ['dịch'],
  駐: ['trú'],
  験: ['nghiệm'],
  高: ['cao'],
  髪: ['phát'],
  魚: ['ngư'],
  鳥: ['điểu'],
  鶏: ['kê'],
  黒: ['hắc'],
};

const han = /[\p{Script=Han}]/u;

export function hanVietFor(text: string) {
  const entries = Array.from(text)
    .filter((character) => han.test(character))
    .map((character) => {
      if (character === '込')
        return '込: chữ Nhật tự tạo, không có âm Hán Việt';
      const readings = hanVietReadings[character];
      if (!readings) return undefined;
      const value = readings
        .map((reading) => reading.toLocaleUpperCase('vi-VN'))
        .join(' / ');
      return `${character}: ${value}`;
    })
    .filter((entry): entry is string => Boolean(entry));

  return entries.length > 0 ? entries.join(' · ') : undefined;
}
